//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DemoxOyModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DemoxOyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DemoxOyEntities object using the connection string found in the 'DemoxOyEntities' section of the application configuration file.
        /// </summary>
        public DemoxOyEntities() : base("name=DemoxOyEntities", "DemoxOyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DemoxOyEntities object.
        /// </summary>
        public DemoxOyEntities(string connectionString) : base(connectionString, "DemoxOyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DemoxOyEntities object.
        /// </summary>
        public DemoxOyEntities(EntityConnection connection) : base(connection, "DemoxOyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lasnaolot> lasnaolots
        {
            get
            {
                if ((_lasnaolots == null))
                {
                    _lasnaolots = base.CreateObjectSet<lasnaolot>("lasnaolots");
                }
                return _lasnaolots;
            }
        }
        private ObjectSet<lasnaolot> _lasnaolots;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lasnaolots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolasnaolots(lasnaolot lasnaolot)
        {
            base.AddObject("lasnaolots", lasnaolot);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoxOyModel", Name="lasnaolot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lasnaolot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lasnaolot object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="asioid">Initial value of the asioid property.</param>
        /// <param name="course">Initial value of the course property.</param>
        public static lasnaolot Createlasnaolot(global::System.Int16 id, global::System.String asioid, global::System.String course)
        {
            lasnaolot lasnaolot = new lasnaolot();
            lasnaolot.id = id;
            lasnaolot.asioid = asioid;
            lasnaolot.course = course;
            return lasnaolot;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int16 _id;
        partial void OnidChanging(global::System.Int16 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String asioid
        {
            get
            {
                return _asioid;
            }
            set
            {
                OnasioidChanging(value);
                ReportPropertyChanging("asioid");
                _asioid = StructuralObject.SetValidValue(value, false, "asioid");
                ReportPropertyChanged("asioid");
                OnasioidChanged();
            }
        }
        private global::System.String _asioid;
        partial void OnasioidChanging(global::System.String value);
        partial void OnasioidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, true, "lastname");
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, true, "firstname");
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, "date");
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String course
        {
            get
            {
                return _course;
            }
            set
            {
                OncourseChanging(value);
                ReportPropertyChanging("course");
                _course = StructuralObject.SetValidValue(value, false, "course");
                ReportPropertyChanged("course");
                OncourseChanged();
            }
        }
        private global::System.String _course;
        partial void OncourseChanging(global::System.String value);
        partial void OncourseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] added
        {
            get
            {
                return StructuralObject.GetValidValue(_added);
            }
            set
            {
                OnaddedChanging(value);
                ReportPropertyChanging("added");
                _added = StructuralObject.SetValidValue(value, true, "added");
                ReportPropertyChanged("added");
                OnaddedChanged();
            }
        }
        private global::System.Byte[] _added;
        partial void OnaddedChanging(global::System.Byte[] value);
        partial void OnaddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateAdded
        {
            get
            {
                return _dateAdded;
            }
            set
            {
                OndateAddedChanging(value);
                ReportPropertyChanging("dateAdded");
                _dateAdded = StructuralObject.SetValidValue(value, "dateAdded");
                ReportPropertyChanged("dateAdded");
                OndateAddedChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateAdded;
        partial void OndateAddedChanging(Nullable<global::System.DateTime> value);
        partial void OndateAddedChanged();

        #endregion

    }

    #endregion

}
