//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace autokantaModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class autokantaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new autokantaEntities object using the connection string found in the 'autokantaEntities' section of the application configuration file.
        /// </summary>
        public autokantaEntities() : base("name=autokantaEntities", "autokantaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new autokantaEntities object.
        /// </summary>
        public autokantaEntities(string connectionString) : base(connectionString, "autokantaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new autokantaEntities object.
        /// </summary>
        public autokantaEntities(EntityConnection connection) : base(connection, "autokantaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Auto> Auto
        {
            get
            {
                if ((_Auto == null))
                {
                    _Auto = base.CreateObjectSet<Auto>("Auto");
                }
                return _Auto;
            }
        }
        private ObjectSet<Auto> _Auto;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Auto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuto(Auto auto)
        {
            base.AddObject("Auto", auto);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autokantaModel", Name="Auto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Auto object.
        /// </summary>
        /// <param name="aid">Initial value of the aid property.</param>
        public static Auto CreateAuto(global::System.Int32 aid)
        {
            Auto auto = new Auto();
            auto.aid = aid;
            return auto;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 aid
        {
            get
            {
                return _aid;
            }
            set
            {
                if (_aid != value)
                {
                    OnaidChanging(value);
                    ReportPropertyChanging("aid");
                    _aid = StructuralObject.SetValidValue(value, "aid");
                    ReportPropertyChanged("aid");
                    OnaidChanged();
                }
            }
        }
        private global::System.Int32 _aid;
        partial void OnaidChanging(global::System.Int32 value);
        partial void OnaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rekkari
        {
            get
            {
                return _rekkari;
            }
            set
            {
                OnrekkariChanging(value);
                ReportPropertyChanging("rekkari");
                _rekkari = StructuralObject.SetValidValue(value, true, "rekkari");
                ReportPropertyChanged("rekkari");
                OnrekkariChanged();
            }
        }
        private global::System.String _rekkari;
        partial void OnrekkariChanging(global::System.String value);
        partial void OnrekkariChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String merkki
        {
            get
            {
                return _merkki;
            }
            set
            {
                OnmerkkiChanging(value);
                ReportPropertyChanging("merkki");
                _merkki = StructuralObject.SetValidValue(value, true, "merkki");
                ReportPropertyChanged("merkki");
                OnmerkkiChanged();
            }
        }
        private global::System.String _merkki;
        partial void OnmerkkiChanging(global::System.String value);
        partial void OnmerkkiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String malli
        {
            get
            {
                return _malli;
            }
            set
            {
                OnmalliChanging(value);
                ReportPropertyChanging("malli");
                _malli = StructuralObject.SetValidValue(value, true, "malli");
                ReportPropertyChanged("malli");
                OnmalliChanged();
            }
        }
        private global::System.String _malli;
        partial void OnmalliChanging(global::System.String value);
        partial void OnmalliChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vm
        {
            get
            {
                return _vm;
            }
            set
            {
                OnvmChanging(value);
                ReportPropertyChanging("vm");
                _vm = StructuralObject.SetValidValue(value, true, "vm");
                ReportPropertyChanged("vm");
                OnvmChanged();
            }
        }
        private global::System.String _vm;
        partial void OnvmChanging(global::System.String value);
        partial void OnvmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> myyntiHinta
        {
            get
            {
                return _myyntiHinta;
            }
            set
            {
                OnmyyntiHintaChanging(value);
                ReportPropertyChanging("myyntiHinta");
                _myyntiHinta = StructuralObject.SetValidValue(value, "myyntiHinta");
                ReportPropertyChanged("myyntiHinta");
                OnmyyntiHintaChanged();
            }
        }
        private Nullable<global::System.Double> _myyntiHinta;
        partial void OnmyyntiHintaChanging(Nullable<global::System.Double> value);
        partial void OnmyyntiHintaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> sisaanOstoHinta
        {
            get
            {
                return _sisaanOstoHinta;
            }
            set
            {
                OnsisaanOstoHintaChanging(value);
                ReportPropertyChanging("sisaanOstoHinta");
                _sisaanOstoHinta = StructuralObject.SetValidValue(value, "sisaanOstoHinta");
                ReportPropertyChanged("sisaanOstoHinta");
                OnsisaanOstoHintaChanged();
            }
        }
        private Nullable<global::System.Double> _sisaanOstoHinta;
        partial void OnsisaanOstoHintaChanging(Nullable<global::System.Double> value);
        partial void OnsisaanOstoHintaChanged();

        #endregion

    }

    #endregion

}
