//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace koeharjotteluModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class koeharjotteluEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new koeharjotteluEntities object using the connection string found in the 'koeharjotteluEntities' section of the application configuration file.
        /// </summary>
        public koeharjotteluEntities() : base("name=koeharjotteluEntities", "koeharjotteluEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new koeharjotteluEntities object.
        /// </summary>
        public koeharjotteluEntities(string connectionString) : base(connectionString, "koeharjotteluEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new koeharjotteluEntities object.
        /// </summary>
        public koeharjotteluEntities(EntityConnection connection) : base(connection, "koeharjotteluEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vehkeet> vehkeet
        {
            get
            {
                if ((_vehkeet == null))
                {
                    _vehkeet = base.CreateObjectSet<vehkeet>("vehkeet");
                }
                return _vehkeet;
            }
        }
        private ObjectSet<vehkeet> _vehkeet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vehkeet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovehkeet(vehkeet vehkeet)
        {
            base.AddObject("vehkeet", vehkeet);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="koeharjotteluModel", Name="vehkeet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vehkeet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vehkeet object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static vehkeet Createvehkeet(global::System.Int32 id)
        {
            vehkeet vehkeet = new vehkeet();
            vehkeet.id = id;
            return vehkeet;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nimi
        {
            get
            {
                return _nimi;
            }
            set
            {
                OnnimiChanging(value);
                ReportPropertyChanging("nimi");
                _nimi = StructuralObject.SetValidValue(value, true, "nimi");
                ReportPropertyChanged("nimi");
                OnnimiChanged();
            }
        }
        private global::System.String _nimi;
        partial void OnnimiChanging(global::System.String value);
        partial void OnnimiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hinta
        {
            get
            {
                return _hinta;
            }
            set
            {
                OnhintaChanging(value);
                ReportPropertyChanging("hinta");
                _hinta = StructuralObject.SetValidValue(value, true, "hinta");
                ReportPropertyChanged("hinta");
                OnhintaChanged();
            }
        }
        private global::System.String _hinta;
        partial void OnhintaChanging(global::System.String value);
        partial void OnhintaChanged();

        #endregion

    }

    #endregion

}
