<%@ Page Title="" Language="C#" MasterPageFile="~/Tehtava-3/PuuMaster.master" AutoEventWireup="true" CodeFile="G2559_puuNakyma.aspx.cs" Inherits="Tehtava_3_G2559_puuNakyma" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <div>
        
        <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" DataSourceID="XmlPolishes">
            <DataBindings>
                <asp:TreeNodeBinding DataMember="nailpolishes" Text="Nailpolish Information" Value="Nailpolish Information" />
                <asp:TreeNodeBinding DataMember="brand" TextField="name" />
                <asp:TreeNodeBinding DataMember="polish" TextField="color" />
                <asp:TreeNodeBinding DataMember="name" TextField="#InnerText" />
            </DataBindings>
        </asp:TreeView>
        <asp:XmlDataSource ID="XmlPolishes" runat="server" DataFile="~/lakat.xml"></asp:XmlDataSource>
        
        </div>
</asp:Content>

